RaidGuild.bossList = {
	["Naxxramas"] = {
		["Anub'Rekhan"] = true,
		["Grand Widow Faerlina"] = true,
		["Maexxna"] = true,
		["Patchwerk"] = true,
		["Grobbulus"] = true,
		["Gluth"] = true,
		["Thaddius"] = true,
		["Instructor Razuvious"] = true,
		["Gothik the Harvester"]  = true,
		["Noth the Plaguebringer"] = true,
		["Heigan the Unclean"]  = true,
		["Loatheb"]  = true,
		["Sapphiron"]  = true,
		["Kel'Thuzad"] = true,
	},
	["The Eye of Eternity"] = {
		["Malygos"] = true,
	},
	["The Obsidian Sanctum"] = {
		["Sartharion"] = true,
	},
	["Ulduar"] = {
		["Flame Leviathan"] = true,
		["Ignis the Furnace Master"] = true,
		["Razorscale"] = true,
		["XT-002 Deconstructor"] = true,
		["Assembly of Iron"] = true,
		["Kologarn"] = true,
		["Auriaya"] = true,
		["Hodir"] = true,
		["Thorim"] = true,
		["Freya"] = true,
		["Mimiron"] = true,
		["General Vezax"] = true,
		["Yogg-Saron"] = true,
		["Algalon the Observer"] = true,
	},
	["Trial of the Crusader"] = {
		["Icehowl"] = true,
		["Fjola Lightbane"] = true,
		["Eydis Darkbane"] = true,
		["Lord Jaraxxus"] = true,
		["Anub'arak"] = true,
	},
	
	["Onyxia's Lair"] = {
		["Onyxia"] = true,
	},
	
}

RaidGuild.itemBoss = {
	["Four Horsemen Chest"]  = "The Four Horsemen",
	["Champions' Cache"] = "Faction Champions",
	["Alexstrasza's Gift"] = "Malygos",
	["Cache of Living Stone"]  ="Kologarn",
	["Cache of Innovation"] = "Mimiron",
	["Cache of Winter"] = "Hodir",
	["Rare Cache of Winter"] = "Hodir (Hardmode)",
	["Cache of Storms"] = "Thorim",
	["Freya's Gift"] = "Freya",
}

RaidGuild.trashList = {
	["Naxxramas"] = {
		["Bile Retcher"] = true,
		["Bile Sludge"] = true,
		["Bony Construct"] = true,
		["Carrion Spinner"] = true,
		["Corpse Scarab"] = true,
		["Crypt Guard"] = true,
		["Crypt Reaver"] = true,
		["Dark Touched Warrior"] = true,
		["Death Knigh"] = true,
		["Death Knight Captain"] = true,
		["Death Knight Cavalier"] = true,
		["Death Knight Understudy	"] = true,
		["Deathcharger Steed"] = true,
		["Deathchill Servant"] = true,
		["Diseased Maggot"] = true,
		["Dread Creeper"] = true,
		["Embalming Slime"] = true,
		["Eye Stalk"] = true,
		["Fallout Slime"] = true,
		["Frenzied Bat"] = true,
		["Guardian of Icecrown"] = true,
		["Infectious Ghoul"] = true,
		["Living Monstrosity"] = true,
		["Mad Scientist"] = true,
		["Maexxna Spiderling"] = true,
		["Marauding Geist"] = true,
		["Mutated Grub"] = true,
		["Naxxramas Acolyte"] = true,
		["Naxxramas Cultist"] = true,
		["Naxxramas Follower"] = true,
		["Naxxramas Worshipper"] = true,
		["Necro Knight"] = true,
		["Necro Stalker"] = true,
		["Patchwork Golem"] = true,
		["Plague Beast"] = true,
		["Plague Slime"] = true,
		["Plagued Bat"] = true,
		["Plagued Champion"] = true,
		["Plagued Construct"] = true,
		["Plagued Guardian"] = true,
		["Plagued Warrior"] = true,
		["Poisonous Skitterer"] = true,
		["Risen Squire"] = true,
		["Rotting Maggot"] = true,
		["Shade of Naxxramas"] = true,
		["Skeletal Smith"] = true,
		["Sludge Belcher"] = true,
		["Soldier of the Frozen Wastes"] = true,
		["Soul Weaver"] = true,
		["Spectral Death Knight"] = true,
		["Spectral Horse"] = true,
		["Spectral Rider"] = true,
		["Spectral Trainee"] = true,
		["Stitched Colossus"] = true,
		["Stitched Giant"] = true,
		["Stoneskin Gargoyle"] = true,
		["Surgical Assistant"] = true,
		["Tomb Horror"] = true,
		["Unholy Axe"] = true,
		["Unholy Staff"] = true,
		["Unholy Swords"] = true,
		["Unrelenting Death Knight"] = true,
		["Unrelenting Rider"] = true,
		["Unrelenting Trainee"] = true,
		["Unstoppable Abomination"] = true,
		["Venom Stalker"] = true,
		["Vigilant Shade"] = true,
		["Web Wrap"] = true,
		["Zombie Chow"] = true,
	},
	["The Obsidian Sanctum"] = {
		["Acolyte of Shadron"] = true,
		["Acolyte of Vesperon"] = true,
		["Disciple of Shadron"] = true,
		["Disciple of Vesperon"] = true,
		["Onyx Blaze Mistress"] = true,
		["Onyx Brood General"] = true,
		["Onyx Flight Captain"] = true,
		["Onyx Sanctum Guardian"] = true,
		["Sartharion Twilight Egg"] = true,
		["Sartharion Twilight Whelp"] = true,
		["Shadron"] = true,
		["Tenebron"] = true,
		["Twilight Egg"] = true,
		["Twilight Whelp"] = true,
		["Vesperon"] = true,
	},
	["The Eye of Eternity"] = {
		["Scion of Eternity"] = true,
	},
	["Ulduar"] = {
		["LOL"] = true,
	},
	["Trial of the Crusader"] = {
		["Gormok the Impaler"] = true,
	},
	
	["Onyxia's Lair"] = {
		["Onyxian Warder"] = true,
	},
	
	
}

RaidGuild.raidZones = {
	["Naxxramas"] = true,
	["The Obsidian Sanctum"] = true,
	["The Nexus: The Eye of Eternity"] = true,
	["Ulduar"] = true,
	["Trial of the Crusader"] = true,
	["Onyxia's Lair"] = true,
}

RaidGuild.raidMeta = {
	["Naxxramas-1"] = {
		["nicename"] = "Naxxramas (10)",
		["maxplayers"] = 10,
	},
	["Naxxramas-2"] = {
		["nicename"] = "Naxxramas (25)",
		["maxplayers"] = 25,
	},
	["The Obsidian Sanctum-1"] = {
		["nicename"] = "The Obsidian Sanctum (10)",
		["maxplayers"] = 10,
	},
	["The Obsidian Sanctum-2"] = {
		["nicename"] = "The Obsidian Sanctum (25)",
		["maxplayers"] = 25,
	},
	["The Eye of Eternity-1"] = {
		["nicename"] = "The Eye of Eternity (10)",
		["maxplayers"] = 10,
	},
	["The Eye of Eternity-2"] = {
		["nicename"] = "The Eye of Eternity (25)",
		["maxplayers"] = 25,
	},
	["Ulduar-1"] = {
		["nicename"] = "Ulduar (10)",
		["maxplayers"] = 10,
	},
	["Ulduar-2"] = {
		["nicename"] = "Ulduar (25)",
		["maxplayers"] = 25,
	},
	["Trial of the Crusader-1"] = {
		["nicename"] = "Trial of the Crusader (10)",
		["maxplayers"] = 10,
	},
	["Trial of the Crusader-2"] = {
		["nicename"] = "Trial of the Crusader (25)",
		["maxplayers"] = 25,
	},
	["Trial of the Crusader-3"] = {
		["nicename"] = "Trial of the Crusader (10 Heroic)",
		["maxplayers"] = 10,
	},
	["Trial of the Crusader-4"] = {
		["nicename"] = "Trial of the Crusader (25 Heroic)",
		["maxplayers"] = 25,
	},
	["Onyxia's Lair-1"] = {
		["nicename"] = "Onyxia (10)",
		["maxplayers"] = 10,
	},
	["Onyxia's Lair-2"] = {
		["nicename"] = "Onyxia (25)",
		["maxplayers"] = 25,
	},
}
